shellspec: show error if not found path

diff --git a/shellspec b/shellspec
--- a/shellspec
+++ b/shellspec
@@ -250,6 +250,7 @@ if [ "$mode" = "runner" ] && [ $# -gt 0 ]; then
       warn "Filtering feature is not currently supported. ($specfile)"
       specfile=${specfile%:*}
     esac
+    [ -e "$specfile" ] || abort "Not found path: $specfile"
     shift
     set -- "$@" "$specfile"
   done
