Fix shell inspection

diff --git a/shellspec b/shellspec
--- a/shellspec
+++ b/shellspec
@@ -66,6 +66,8 @@ export SHELLSPEC_PROFILER=''
 export SHELLSPEC_PROFILER_LOG=''
 export SHELLSPEC_PROFILER_LIMIT=10
 export SHELLSPEC_PROFILER_REPORT="profiler.log"
+export SHELLSPEC_DEFECT_ARITHMETIC=''
+export SHELLSPEC_DEFECT_SIGNALS=''
 export SHELLSPEC_DEFECT_READONLY=''
 export SHELLSPEC_DEFECT_REDEFINE=''
 export SHELLSPEC_DEFECT_SHELL_FLAG=''
@@ -384,44 +386,46 @@ if [ -z "$SHELLSPEC_SHELL" ]; then
   warn "Use 'sh' instead. You can specify the shell with --shell option."
 fi
 
-#shellcheck disable=SC2123
-# posh 0.8.5 implements kill but not support any signals. meaningless.
-if [ ! "$(PATH=; (kill -l) 2>/dev/null)" ]; then
-  SHELLSPEC_KILL=$(command_path kill) ||:
-fi
-if [ ! "$SHELLSPEC_KILL" ]; then
-  # e.g. posh 0.13.2 not implement kill, and debian 10 not install kill.
-  warn "kill not found. You may encounter errors with some features."
-  SHELLSPEC_KILL="kill"
-fi
-
 shell=$(command_path "${SHELLSPEC_SHELL:-sh}") ||:
 if ! [ -x "${shell%% *}" ]; then
   abort "Not found specified shell: $SHELLSPEC_SHELL"
 fi
 SHELLSPEC_SHELL=$shell
 
-if ! $SHELLSPEC_SHELL -c 'exit $((0))' 2>/dev/null; then
-  abort "Unsupported shell (require arithmetic expansion): $SHELLSPEC_SHELL"
-fi
+{
+  eval "$($SHELLSPEC_SHELL "$SHELLSPEC_LIBEXEC/shellspec-inspection.sh")"
 
-if ! (false() { :; }; false) 2>/dev/null; then
-  warn "Unsupported shell (builtin commands can not redefine): $SHELLSPEC_SHELL"
-  SHELLSPEC_DEFECT_REDEFINE=1
-fi
+  if [ "$SHELLSPEC_DEFECT_ARITHMETIC" ]; then
+    abort "Unsupported shell (arithmetic expansion not supported)"
+  fi
 
-#shellcheck disable=SC2034,SC2234
-if ( [ "$( ( readonly value=123 ) 2>&1 )" ] ) 2>/dev/null; then
-  # Workaround for pdksh 5.2.14 (debian-2.2), ksh 93q, ksh 93r.
-  # Still working but not officially supported.
-  warn "Unsupported shell (defect of readonly): $SHELLSPEC_SHELL"
-  SHELLSPEC_DEFECT_READONLY=1
-fi
+  if [ "$SHELLSPEC_DEFECT_SIGNALS" ];then
+    # posh 0.8.5 implements kill but not support any signals. meaningless.
+    SHELLSPEC_KILL=$(command_path kill) ||:
+    if [ ! "$SHELLSPEC_KILL" ]; then
+      # For example posh 0.13.2 does not implement kill as builtin
+      # and debian 10 docker image does not have kill command installed.
+      warn "kill not found. You may encounter errors with some features."
+      SHELLSPEC_KILL="kill"
+    fi
+  fi
 
-if $SHELLSPEC_SHELL -c 'set -u; unset v ||:; : $v' 2>/dev/null; then
-  warn "Unsupported shell (shell flag handling broken): $SHELLSPEC_SHELL"
-  SHELLSPEC_DEFECT_SHELL_FLAG=1
-fi
+  if [ "$SHELLSPEC_DEFECT_REDEFINE" ]; then
+    # busybox 1.1.3
+    warn "Unsupported shell (builtin commands can not redefine)"
+  fi
+
+  if [ "$SHELLSPEC_DEFECT_READONLY" ]; then
+    # pdksh 5.2.14 (debian-2.2), ksh 93q, ksh 93r
+    # busybox 1.15.3, busybox 1.19.4
+    warn "Unsupported shell (readonly malfunction)"
+  fi
+
+  if [ "$SHELLSPEC_DEFECT_SHELL_FLAG" ]; then
+    # posh 0.10.2
+    warn "Unsupported shell (shell flag handling broken)"
+  fi
+}
 
 if "$SHELLSPEC_LIBEXEC/shellspec-shebang" 2>/dev/null; then
   SHELLSPEC_SHEBANG_MULTIARG=1
