shellspec --list supports display examples with id

diff --git a/shellspec b/shellspec
--- a/shellspec
+++ b/shellspec
@@ -29,6 +29,7 @@ export SHELLSPEC_DRYRUN=''
 export SHELLSPEC_FOCUS=''
 export SHELLSPEC_BANNER=''
 export SHELLSPEC_MODE='runner'
+export SHELLSPEC_LIST=''
 export SHELLSPEC_ENV_FROM=''
 export SHELLSPEC_PATTERN="*_spec.sh"
 export SHELLSPEC_UNIXTIME=''
@@ -86,10 +87,10 @@ Usage: ${0##*/} [options] [files or directories]
   -e, --env NAME=VALUE                Set environment variable
       --env-from ENV-SCRIPT           Set environment variable from script file
   -w, --warnings LEVEL                Set warnings level
-                                        none (do not show warnings)
-                                        notice (show warnings but not treats as error)
-                                        error (show warnings and treats as error) [default]
-                                        failure (treats warnings as failures)
+                                        [none]    (do not show warnings)
+                                        [notice]  (show warnings but not treats as error)
+                                        [error]   (show warnings and treats as error) [default]
+                                        [failure] (treats warnings as failures)
   -j, --jobs JOBS                     Number of parallel jobs to run (0 jobs means disabled)
       --dry-run                       Print the formatter output without running any examples
 
@@ -97,17 +98,17 @@ Usage: ${0##*/} [options] [files or directories]
 
       --[no-]banner                   Show banner if exist 'spec/banner' [default: enabled]
   -f, --format FORMATTER              Choose a formatter.
-                                        [p]rogress (dots) [default]
-                                        [d]ocumentation (group and example names)
-                                        [t]ap
-                                        debug (for developer)
+                                        [progress]      (dots) [default]
+                                        [documentation] (group and example names)
+                                        [tap]           (TAP format)
+                                        [debug]         (for developer)
                                         custom formatter name
       --force-color, --force-colour   Force the output to be in color, even if the output is not a TTY
       --no-color, --no-colour         Force the output to not be in color, even if the output is a TTY
       --skip-message VERBOSE          Mute skip message
-                                        none (do not mute any messages) [default]
-                                        moderate (mute repeated messages)
-                                        quiet (mute repeated messages and non-temporarily messages)
+                                        [none]     (do not mute any messages) [default]
+                                        [moderate] (mute repeated messages)
+                                        [quiet]    (mute repeated messages and non-temporarily messages)
 
   **** Filtering ****
 
@@ -123,8 +124,10 @@ Usage: ${0##*/} [options] [files or directories]
 
       --init                          Initialize your project with shellspec
       --count                         Count the number of specfiles and examples
-      --list-specfiles                List the specfiles
-      --list-examples                 List the examples
+      --list LIST                     List the specfiles / examples
+                                        [specfiles]       (List the specfiles)
+                                        [examples:id]     (List the examples with id)
+                                        [examples:lineno] (List the examples with lineno)
       --syntax-check                  Syntax check of the specfiles without running any examples
       --translate                     Output translated specfile
       --task [TASK]                   Run task. If TASK is not specified, show the task list
@@ -197,8 +200,14 @@ parse_options() {
       --no-fail-fast) SHELLSPEC_FAIL_FAST_COUNT='' ;;
       --fail-no-examples) SHELLSPEC_FAIL_NO_EXAMPLES=1 ;;
       --no-fail-no-examples) SHELLSPEC_FAIL_NO_EXAMPLES='' ;;
-      --init | --task | --translate | --syntax-check | \
-      --count | --list-specfiles | --list-examples) SHELLSPEC_MODE=${1#--} ;;
+      --init | --task | --translate | --syntax-check) SHELLSPEC_MODE=${1#--} ;;
+      --count) SHELLSPEC_MODE=list SHELLSPEC_LIST='' ;;
+      --list) [ $# -ge 2 ] || abort 'Require LIST.'
+        case $2 in (specfiles|examples:id|examples:lineno) ;;
+          *) abort 'Invalid LIST.'
+        esac
+        SHELLSPEC_MODE=list SHELLSPEC_LIST=$2
+        shift ;;
       -h | --help) usage && exit 0;;
       -v | --version) echo "$SHELLSPEC_VERSION" && exit 0 ;;
       -*) abort "Unknown option '$1'" ;;
