Add path syntax to match recursive directories

diff --git a/shellspec b/shellspec
--- a/shellspec
+++ b/shellspec
@@ -338,6 +338,24 @@ fi
 
 case $SHELLSPEC_MODE in (runner | list | translate | syntax-check)
   [ $# -eq 0 ] && set -- "$SHELLSPEC_DEFAULT_PATH"
+  if includes_pathstar "$@"; then
+    for p in "$@"; do
+      includes_pathstar "$p" || continue
+      check_pathstar "$p" || abort "The path pattern is invalid: $p."
+    done
+    args='' arg=''
+    callback() {
+      if [ ! "$2" ] || [ -e "${1%%:*}" ]; then
+        escape_quote arg "$1"
+        args="$args $arg"
+      fi
+    }
+    cd "$SHELLSPEC_CWD"
+    expand_pathstar callback "." "$@"
+    cd "$SHELLSPEC_PROJECT_ROOT"
+    eval "set -- $args"
+    [ $# -eq 0 ] && abort "Did not match the specified path(s)."
+  fi
   for p in "$@"; do
     abspath='' range=''
     abspath abspath "$p" "$SHELLSPEC_CWD"
