Add tap generator

diff --git a/shellspec b/shellspec
--- a/shellspec
+++ b/shellspec
@@ -16,6 +16,7 @@ export SHELLSPEC_TMPBASE=''
 export SHELLSPEC_TIME_LOG=''
 export SHELLSPEC_EXAMPLES_LOG=''
 export SHELLSPEC_FORMATTER='progress'
+export SHELLSPEC_GENERATORS=''
 export SHELLSPEC_COLOR=''
 export SHELLSPEC_REQUIRES=''
 export SHELLSPEC_SPEC_FAILURE_CODE=101
@@ -109,12 +110,14 @@ Usage: shellspec [options] [files or directories]
   **** Output ****
 
       --[no-]banner                   Show banner if exist 'spec/banner' [default: enabled]
-  -f, --format FORMATTER              Choose a formatter.
+  -f, --format FORMATTER              Choose a formatter to use for display.
                                         [p]rogress      dots [default]
                                         [d]ocumentation group and example names
                                         [t]ap           TAP format
                                         [debug]         for developer
                                         custom formatter name
+  -o, --output GENERATOR              Choose a generator(s) to generate a report.
+                                        [tap]           TAP format
       --force-color, --force-colour   Force the output to be in color, even if the output is not a TTY
       --no-color, --no-colour         Force the output to not be in color, even if the output is a TTY
       --skip-message VERBOSE          Mute skip message
@@ -169,6 +172,10 @@ parse_options() {
         for format in progress documentation tap; do
           case $format in ($2*) SHELLSPEC_FORMATTER=$format; esac
         done
+        shift ;;
+      -o | --output) [ "${2:-}" ] || abort 'Require GENERATOR.'
+        case $2 in (*[!a-z0-9_-]*) abort 'Invalid generator name.'; esac
+        SHELLSPEC_GENERATORS="$SHELLSPEC_GENERATORS $2"
         shift ;;
       --force-color | --force-colour) SHELLSPEC_COLOR=1 ;;
       --no-color | --no-colour) SHELLSPEC_COLOR='' ;;
