Implement randomize the order with shuf

diff --git a/shellspec b/shellspec
--- a/shellspec
+++ b/shellspec
@@ -39,6 +39,9 @@ export SHELLSPEC_UNIXTIME=''
 export SHELLSPEC_TMPDIR=${TMPDIR:-/tmp}
 export SHELLSPEC_LOGFILE=/dev/tty
 export SHELLSPEC_DEFAULT_PATH=spec
+export SHELLSPEC_INFILE=file
+export SHELLSPEC_RANDOM=''
+export SHELLSPEC_SEED=''
 
 readlinkf() {
   p=$1 i=0
@@ -83,7 +86,7 @@ fi
 
 usage() {
 while IFS= read -r line; do echo "$line"; done <<USAGE
-Usage: ${0##*/} [options] [files or directories]
+Usage: shellspec [options] [files or directories]
 
   -s, --shell SHELL                   Specify a path of shell [default: current shell]
       --[no-]fail-fast[=COUNT]        Abort the run after a certain number of failures [default: 1]
@@ -91,29 +94,33 @@ Usage: ${0##*/} [options] [files or directories]
   -r, --require MODULE                Require a file
   -e, --env NAME=VALUE                Set environment variable
       --env-from ENV-SCRIPT           Set environment variable from script file
-  -w, --warnings LEVEL                Set warnings level
-                                        [none]    (do not show warnings)
-                                        [notice]  (show warnings but not treats as error)
-                                        [error]   (show warnings and treats as error) [default]
-                                        [failure] (treats warnings as failures)
+      --random TYPE[:SEED]            Run examples by the specified random type
+                                        [none]      examples and groups are run in the order they are defined [default]
+                                        [specfiles] randomize the order of specfiles
+                                        [examples]  randomize the order of examples (slow)
   -j, --jobs JOBS                     Number of parallel jobs to run (0 jobs means disabled)
+  -w, --warnings LEVEL                Set warnings level
+                                        [none]    do not show warnings
+                                        [notice]  show warnings but not treats as error
+                                        [error]   show warnings and treats as error [default]
+                                        [failure] treats warnings as failures
       --dry-run                       Print the formatter output without running any examples
 
   **** Output ****
 
       --[no-]banner                   Show banner if exist 'spec/banner' [default: enabled]
   -f, --format FORMATTER              Choose a formatter.
-                                        [p]rogress      (dots) [default]
-                                        [d]ocumentation (group and example names)
-                                        [t]ap           (TAP format)
-                                        [debug]         (for developer)
+                                        [p]rogress      dots [default]
+                                        [d]ocumentation group and example names
+                                        [t]ap           TAP format
+                                        [debug]         for developer
                                         custom formatter name
       --force-color, --force-colour   Force the output to be in color, even if the output is not a TTY
       --no-color, --no-colour         Force the output to not be in color, even if the output is a TTY
       --skip-message VERBOSE          Mute skip message
-                                        [none]     (do not mute any messages) [default]
-                                        [moderate] (mute repeated messages)
-                                        [quiet]    (mute repeated messages and non-temporarily messages)
+                                        [none]     do not mute any messages [default]
+                                        [moderate] mute repeated messages
+                                        [quiet]    mute repeated messages and non-temporarily messages
 
   **** Ranges / Filters ****
 
@@ -137,10 +144,11 @@ Usage: ${0##*/} [options] [files or directories]
       --init                          Initialize your project with shellspec
       --count                         Count the number of specfiles and examples
       --list LIST                     List the specfiles / examples
-                                        [specfiles]       (List the specfiles)
-                                        [examples:id]     (List the examples with id)
-                                        [examples:lineno] (List the examples with lineno)
-                                        [debug]           (for developer)
+                                        [specfiles]       list the specfiles
+                                        [examples]        list the examples with id
+                                        [examples:id]     alias for examples
+                                        [examples:lineno] list the examples with lineno
+                                        [debug]           for developer
       --syntax-check                  Syntax check of the specfiles without running any examples
       --translate                     Output translated specfile
       --task [TASK]                   Run task. If TASK is not specified, show the task list
@@ -165,6 +173,14 @@ parse_options() {
       --no-color | --no-colour) SHELLSPEC_COLOR='' ;;
       -s | --shell) [ "${2:-}" ] || abort 'Require SHELL.'
         SHELLSPEC_SHELL=$2
+        shift ;;
+      --random) [ "${2:-}" ] || abort 'Require TYPE[:SEED].'
+        case ${2%%:*} in
+          none) SHELLSPEC_RANDOM='' ;;
+          specfiles|examples) SHELLSPEC_RANDOM=${2%%:*} ;;
+          *) abort 'Invalid TYPE[:SEED].'
+        esac
+        case $2 in (*:*) SHELLSPEC_SEED=${2#*:} ;; (*) SHELLSPEC_SEED=''; esac
         shift ;;
       -j | --jobs) [ "${2:-}" ] || abort 'Require JOBS.'
         SHELLSPEC_JOBS=$2
@@ -230,7 +246,7 @@ parse_options() {
       --init | --task | --translate | --syntax-check) SHELLSPEC_MODE=${1#--} ;;
       --count) SHELLSPEC_MODE=list SHELLSPEC_LIST='' ;;
       --list) [ "${2:-}" ] || abort 'Require LIST.'
-        case $2 in (specfiles|examples:id|examples:lineno|debug) ;;
+        case $2 in (specfiles|examples|examples:id|examples:lineno|debug) ;;
           *) abort 'Invalid LIST.'
         esac
         SHELLSPEC_MODE=list SHELLSPEC_LIST=$2
